### ISSUE TITLE
Crash: Ticking Entity

### ISSUE THREAD

**Issue by AzureMonument** [sf-inc/sihywtcamc#18]
Here's the crash log:

Time: 4/11/21 1:14 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at mod.wittywhiscash.damageoverhaul.common.modules.damage.util.DamageUtils.getDamageAfterTypedArmor(DamageUtils.java:99)
	at net.minecraft.class_1309.redirect$dib000$performArmorAndEnchantmentCalc(class_1309.java:20390)
	at net.minecraft.class_1309.method_6074(class_1309.java:1549)
	at net.minecraft.class_1309.method_5643(class_1309.java:1035)
	at net.minecraft.class_1309.method_5670(class_1309.java:331)
	at net.minecraft.class_1308.method_5670(class_1308.java:275)
	at net.minecraft.class_1297.method_5773(class_1297.java:431)
	at net.minecraft.class_1309.method_5773(class_1309.java:2209)
	at net.minecraft.class_1308.method_5773(class_1308.java:342)
	at net.minecraft.class_1621.method_5773(class_1621.java:139)
	at net.minecraft.class_3218.method_18762(class_3218.java:621)
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_3218.method_18765(class_3218.java:411)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.handler$cjh000$modifiedRunLoop(MinecraftServer.java:7810)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:651)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at mod.wittywhiscash.damageoverhaul.common.modules.damage.util.DamageUtils.getDamageAfterTypedArmor(DamageUtils.java:99)
	at net.minecraft.class_1309.redirect$dib000$performArmorAndEnchantmentCalc(class_1309.java:20390)
	at net.minecraft.class_1309.method_6074(class_1309.java:1549)
	at net.minecraft.class_1309.method_5643(class_1309.java:1035)
	at net.minecraft.class_1309.method_5670(class_1309.java:331)
	at net.minecraft.class_1308.method_5670(class_1308.java:275)
	at net.minecraft.class_1297.method_5773(class_1297.java:431)
	at net.minecraft.class_1309.method_5773(class_1309.java:2209)
	at net.minecraft.class_1308.method_5773(class_1308.java:342)
	at net.minecraft.class_1621.method_5773(class_1621.java:139)
	at net.minecraft.class_3218.method_18762(class_3218.java:621)

-- Entity being ticked --
Details:
	Entity Type: biomemakeover:giant_slime (party.lemons.biomemakeover.entity.GiantSlimeEntity)
	Entity ID: 5116
	Entity Name: Giant Slime
	Entity's Exact location: 833.92, 51.00, 580.92
	Entity's Block location: World: (833,51,580), Chunk: (at 1,3,4 in 52,36; contains blocks 832,0,576 to 847,255,591), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_3218.method_18765(class_3218.java:411)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Aojae'/213, l='ServerWorld minecraft:overworld World Gen Test Five', x=771.77, y=129.72, z=644.66]]
	Chunk stats: ServerChunkCache: 4104
	Level dimension: minecraft:overworld
	Level spawn location: World: (256,86,176), Chunk: (at 0,5,0 in 16,11; contains blocks 256,0,176 to 271,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2596 game time, 2596 day time
	Level name: World Gen Test Five
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 174149 (now: false), thunder time: 45769 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.handler$cjh000$modifiedRunLoop(MinecraftServer.java:7810)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:651)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Unknown Source)

I'm running 1.16.5 MC, Fabric 0.11.3, FabricAPI 0.32.5, and sihywtcamc 1.2
I also have other mods (like biome makeover and simplex).

**Comment by charlyb01** [comment]
Okay so as it is written (but you didn't see), the problem is from [Damage Overhaul](https://www.curseforge.com/minecraft/mc-mods/damage-overhaul) mod. I don't know what made you think it was my mod causing the problem, but I'll let you share this report with the right person =)

**Comment by AzureMonument** [comment]
.... I have no idea why I am on this issue tracker. Somehow I thought this was Damage Overhaul. Woops.
